language: php
matrix:
  include:
    - php: 7.1

sudo: false
before_install:
  - export NEOS_TARGET_VERSION=3.3
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction dl/assetsync:2.1
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/DL.AssetSync
  - mv dl-assetsync neos-base-distribution/Packages/Application/DL.AssetSync
  - cd neos-base-distribution
script:
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/DL.AssetSync/Tests/Functional
