DL:
  AssetSync:
    sourceConfiguration:
#      localFileSyncSource:
#        sourceClass: DL\AssetSync\Source\LocalFilesystemSource
#        fileIdentifierPattern: '.+\.(gif|jpg|jpeg|tiff|png)'
#        removeAssetsNotInSource: false
#        assetTags:
#          - myLocalFileSource
#        assetCollections:
#          - localFileSourceSync
#        sourceOptions:
#          sourcePath: '%FLOW_PATH_DATA%FileSyncSource'


