DL:
  AssetSync:
    sourceConfiguration:
#      localFileSyncSource:
#        sourceClass: DL\AssetSync\Source\LocalFilesystemSource
#        fileIdentifierPattern: '.+\.(gif|jpg|jpeg|tiff|png)'
#        assetTags:
#          - myLocalFileSource
#        sourceOptions:
#          sourcePath: '%FLOW_PATH_DATA%FileSyncSource'

